kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: springbootdemo
  namespace: demo
spec:
  hosts:
    - qing.ppdai.com
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            prefix: /static
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
        - uri:
            exact: /productpage
        - uri:
            exact: /health
      route:
        - destination:
            host: productpage
            port:
              number: 9080
